### PR TITLE
flatpak-autoinstall: Install org.gnome.gedit on OS upgrade

### PR DESCRIPTION
**Pull request by starnight**
Move gedit from deb package to flatpak app.

https://phabricator.endlessm.com/T32879

### CODE REVIEW

**Review by jprvita — CHANGES_REQUESTED** [review]
I think we should add this entry to a separate `50-gedit.json` file, instead of adding it to `50-default.json`, similarly to what was done for showell / cheese etc,so if the user wants to override it for some reason it is easy to do it.

But it should be ordered at 50, as AFAIU there is no reason to force an ordering here by using a different number (IMO rhythmbox, cheese and shotwell should also have been orderd at 50).

**Review by GeorgesStavracas — APPROVED** [review]
LGTM

**Review by jprvita — CHANGES_REQUESTED** [review]
You also need to add this new file to Makefile.am.

**Comment by starnight** [comment]
Thanks for catching it!

**Review by jprvita — APPROVED** [review]

**Pull request merged**
