### PR TITLE
flatpak-autoinstall: Install org.chromium.Chromium on OS upgrade

### PR DESCRIPTION
**Pull request by andrunko**
https://phabricator.endlessm.com/T30997

### CODE REVIEW

**Comment by andrunko** [comment]
Converted to draft as I think we should only merge this and related changes once chromium hits flathub stable (atm we don't configure a flathub-beta remote and thus can't install it).

Appreciate any comments in the meantime.

**Review by wjt — APPROVED** [review]

**Comment by wjt** [comment]
I think this will need a rebase.

**Comment by andrunko** [comment]
> I think this will need a rebase.

Yes, I will rebase once we are ready to land on master just in case it changes again.

**Comment by andrunko** [comment]
Actually rebased already on latest master but may require a new rebase depending on when it lands.

**Comment by wjt** [comment]
We could avoid the need for these repeated rebases in future by putting things into different files. e.g. this could live in a `50-chromium.json` file.

**Pull request merged**
