### PR TITLE
flatpak-autoinstall: update com.hack_computer.Clubhouse

### PR DESCRIPTION
**Pull request by erikos**
The Clubhouse should be updated with 3.9.0 to ensure that it works with the recent hack extension changes.

https://phabricator.endlessm.com/T30957

### CODE REVIEW

**Comment by wjt** [comment]
Do you want to wait to merge this until the new Clubhouse is released?

**Comment by erikos** [comment]
> Do you want to wait to merge this until the new Clubhouse is released?

Does it matter? In which case would it fail? Or just to be able to test it first https://phabricator.endlessm.com/T30957#856706

**Comment by wjt** [comment]
It is a one-time update. Suppose we merge this change and release it in beta2, but not release the fixed clubhouse. Then when a user updates the OS to beta2, they will just get whatever the latest clubhouse happens to be. When we eventually do release a fixed clubhouse, they will not automatically get it (except through the normal app update mechanism)

**Comment by erikos** [comment]
> It is a one-time update. Suppose we merge this change and release it in beta2, but not release the fixed clubhouse. Then when a user updates the OS to beta2, they will just get whatever the latest clubhouse happens to be. When we eventually do release a fixed clubhouse, they will not automatically get it (except through the normal app update mechanism)

Ok, let's sync it with the release then.

**Pull request closed without merging**
